name: ci
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/**.yaml'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/**.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: Test
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./out/coverprofile.out
